import type { JudgeResult, RunReport, Transcript } from "../types.js";

function avg(nums: number[]): number {
  return nums.length ? nums.reduce((a, b) => a + b, 0) / nums.length : 0;
}

function scoreEmoji(score: number): string {
  if (score >= 4) return "🟢";
  if (score >= 3) return "🟡";
  return "🔴";
}

function resultsFor(report: RunReport, scenarioId: string): JudgeResult[] {
  return report.judgeResults.filter((r) => r.scenarioId === scenarioId);
}

function transcriptSection(t: Transcript, results: JudgeResult[]): string {
  const verdicts = results
    .map(
      (r) =>
        `**${r.rubric}** ${scoreEmoji(r.score)} ${r.score}/5 — ${r.reasoning}` +
        (r.evidence.length
          ? `\n${r.evidence.map((e) => `  > ${e}`).join("\n")}`
          : ""),
    )
    .join("\n\n");

  const turns = t.turns
    .map((turn) => `**${turn.role === "user" ? "🧑 Customer" : "🤖 Agent"}:** ${turn.content}`)
    .join("\n\n");

  return [
    `### \`${t.scenarioId}\` — ${t.goal}`,
    `End reason: \`${t.endReason}\` · Median agent latency: ${median(t.targetLatencyMs)}ms`,
    verdicts,
    `<details><summary>Full transcript (${t.turns.length} turns)</summary>\n\n${turns}\n\n</details>`,
  ].join("\n\n");
}

function median(nums: number[]): number {
  if (!nums.length) return 0;
  const sorted = [...nums].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

export function renderReport(report: RunReport): string {
  const rows = report.transcripts.map((t) => {
    const rs = resultsFor(report, t.scenarioId);
    const byRubric = (rubric: string) => {
      const r = rs.find((x) => x.rubric === rubric);
      return r ? `${scoreEmoji(r.score)} ${r.score}/5` : "—";
    };
    return `| \`${t.scenarioId}\` | ${t.personaKey} | ${t.endReason} | ${byRubric(
      "task-completion",
    )} | ${byRubric("groundedness")} | ${byRubric("tone-policy")} |`;
  });

  return [
    `# 🔴 RedDial Report`,
    ``,
    `**Target:** \`${report.target}\` · **Started:** ${report.startedAt} · **Overall: ${report.overallScore}/100**`,
    ``,
    `| Scenario | Persona | End | Task | Grounded | Tone/Policy |`,
    `|---|---|---|---|---|---|`,
    ...rows,
    ``,
    `## Scenario details`,
    ``,
    ...report.transcripts.map((t) => transcriptSection(t, resultsFor(report, t.scenarioId))),
    ``,
    `---`,
    `Generated by [RedDial](https://github.com/chokonaira/reddial) — adversarial simulation & eval harness for conversational agents.`,
  ].join("\n");
}

export function overallScore(results: JudgeResult[]): number {
  return Math.round((avg(results.map((r) => r.score)) / 5) * 100);
}
